sudo: false
language: c

# http://docs.haskellstack.org/en/stable/travis_ci/#container-infrastructure
cache:
  directories:
    - $HOME/.stack
    - $HOME/.ghc

before_install:
  - unset CC
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - mkdir -p /tmp/notmuch
  - curl -L https://notmuchmail.org/releases/notmuch-$NOTMUCHVER.tar.gz | tar xz --wildcards --strip-components=1 -C /tmp/notmuch
  - pushd /tmp/notmuch && ./configure --prefix=/usr --without-emacs --without-ruby && make && sudo make install && popd

script:
  - stack $STACK_ARGS --system-ghc --no-terminal --skip-ghc-check install
  - DEBUG=1 stack $STACK_ARGS --system-ghc --no-terminal --skip-ghc-check test 2> /tmp/test.log
  - cat /tmp/test.log
  - stack $STACK_ARGS --system-ghc --no-terminal --skip-ghc-check haddock

matrix:
  include:
  - env: STACK_ARGS="--resolver lts-8" NOTMUCHVER=0.24.2
    compiler: ": #stack lts-8 - notmuch: 0.24.2"
    addons: {apt: {packages: [ghc-8.0.2, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}

  - env: STACK_ARGS="--resolver lts-8" NOTMUCHVER=0.25
    compiler: ": #stack lts-8 - notmuch: 0.25"
    addons: {apt: {packages: [ghc-8.0.2, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}

  - env: STACK_ARGS="--resolver lts-9" NOTMUCHVER=0.24.2
    compiler: ": #stack lts-9 - notmuch: 0.24.2"
    addons: {apt: {packages: [ghc-8.0.2, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}

  - env: STACK_ARGS="--resolver lts-9" NOTMUCHVER=0.25
    compiler: ": #stack lts-9 - notmuch: 0.25"
    addons: {apt: {packages: [ghc-8.0.2, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}

  - env: STACK_ARGS="--resolver nightly" NOTMUCHVER=0.24.2
    compiler: ": #stack nightly - notmuch: 0.24.2"
    addons: {apt: {packages: [ghc-8.2.1, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}

  - env: STACK_ARGS="--resolver nightly" NOTMUCHVER=0.25
    compiler: ": #stack nightly - notmuch: 0.25"
    addons: {apt: {packages: [ghc-8.2.1, tmux, g++, libxapian-dev, libgmime-2.6-dev, libtalloc-dev, zlib1g-dev], sources: [hvr-ghc]}}
